---
- name: Create postfix configuration directory
  ansible.builtin.file:
    path: "{{ nginx_php_base_path }}/data/postfix"
    state: directory
    recurse: yes
    owner: root
    group: root

- name: Configure postfix main.cf
  ansible.builtin.template:
    src: postfix-main.cf.j2
    dest: "{{ nginx_php_base_path }}/data/postfix/main.cf"
    owner: root
    group: root
    mode: 0644
  notify: postmap reload

- name: Configure postfix sasl_passwd
  ansible.builtin.template:
    src: postfix-sasl_passwd.j2
    dest: "{{ nginx_php_base_path }}/data/postfix/sasl_passwd"
    owner: root
    group: root
    mode: 0600
  notify: postmap reload

- name: Configure postfix generic
  ansible.builtin.template:
    src: postfix-generic.j2
    dest: "{{ nginx_php_base_path }}/data/postfix/generic"
    owner: root
    group: root
    mode: 0644
  notify: postmap reload

- name: Configure postfix relayhost_map
  ansible.builtin.template:
    src: postfix-relayhost_map.j2
    dest: "{{ nginx_php_base_path }}/data/postfix/relayhost_map"
    owner: root
    group: root
    mode: 0644
  notify: postmap reload

- name: Configure postfix aliases
  ansible.builtin.lineinfile:
    dest: "{{ nginx_php_base_path }}/data/postfix/aliases"
    regexp: "^root"
    line: "root: {{ root_mail }}"
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644
  notify: postmap reload
